BEGIN;
--
-- Create model Color
--
CREATE TABLE "ie_color" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "color" varchar(200) NOT NULL);
--
-- Create model Date
--
CREATE TABLE "ie_date" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL);
--
-- Create model Loc
--
CREATE TABLE "ie_loc" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "place_name" varchar(200) NOT NULL, "coordinates" geometry(POINT,4326) NOT NULL);
--
-- Create model Time
--
CREATE TABLE "ie_time" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "time" time NOT NULL);
--
-- Create model Type
--
CREATE TABLE "ie_type" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type" varchar(200) NOT NULL);
--
-- Create model Report
--
CREATE TABLE "ie_report" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "record_created" timestamp with time zone NOT NULL, "last_mod" timestamp with time zone NOT NULL, "source_name" varchar(200) NOT NULL, "source_url" varchar(200) NOT NULL, "obs_txt" text NOT NULL);
CREATE TABLE "ie_report_obs_colors" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "report_id" bigint NOT NULL, "color_id" bigint NOT NULL);
CREATE TABLE "ie_report_obs_dates" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "report_id" bigint NOT NULL, "date_id" bigint NOT NULL);
CREATE TABLE "ie_report_obs_locs" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "report_id" bigint NOT NULL, "loc_id" bigint NOT NULL);
CREATE TABLE "ie_report_obs_times" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "report_id" bigint NOT NULL, "time_id" bigint NOT NULL);
CREATE TABLE "ie_report_obs_types" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "report_id" bigint NOT NULL, "type_id" bigint NOT NULL);
CREATE INDEX "ie_loc_coordinates_1d8f18e6_id" ON "ie_loc" USING GIST ("coordinates");
ALTER TABLE "ie_report_obs_colors" ADD CONSTRAINT "ie_report_obs_colors_report_id_color_id_3ec01436_uniq" UNIQUE ("report_id", "color_id");
ALTER TABLE "ie_report_obs_colors" ADD CONSTRAINT "ie_report_obs_colors_report_id_36c096ff_fk_ie_report_id" FOREIGN KEY ("report_id") REFERENCES "ie_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ie_report_obs_colors" ADD CONSTRAINT "ie_report_obs_colors_color_id_4bf5bbb6_fk_ie_color_id" FOREIGN KEY ("color_id") REFERENCES "ie_color" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ie_report_obs_colors_report_id_36c096ff" ON "ie_report_obs_colors" ("report_id");
CREATE INDEX "ie_report_obs_colors_color_id_4bf5bbb6" ON "ie_report_obs_colors" ("color_id");
ALTER TABLE "ie_report_obs_dates" ADD CONSTRAINT "ie_report_obs_dates_report_id_date_id_9205751c_uniq" UNIQUE ("report_id", "date_id");
ALTER TABLE "ie_report_obs_dates" ADD CONSTRAINT "ie_report_obs_dates_report_id_cca4a0cb_fk_ie_report_id" FOREIGN KEY ("report_id") REFERENCES "ie_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ie_report_obs_dates" ADD CONSTRAINT "ie_report_obs_dates_date_id_3d8abaa2_fk_ie_date_id" FOREIGN KEY ("date_id") REFERENCES "ie_date" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ie_report_obs_dates_report_id_cca4a0cb" ON "ie_report_obs_dates" ("report_id");
CREATE INDEX "ie_report_obs_dates_date_id_3d8abaa2" ON "ie_report_obs_dates" ("date_id");
ALTER TABLE "ie_report_obs_locs" ADD CONSTRAINT "ie_report_obs_locs_report_id_loc_id_b5ddb83e_uniq" UNIQUE ("report_id", "loc_id");
ALTER TABLE "ie_report_obs_locs" ADD CONSTRAINT "ie_report_obs_locs_report_id_476fc202_fk_ie_report_id" FOREIGN KEY ("report_id") REFERENCES "ie_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ie_report_obs_locs" ADD CONSTRAINT "ie_report_obs_locs_loc_id_df22e215_fk_ie_loc_id" FOREIGN KEY ("loc_id") REFERENCES "ie_loc" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ie_report_obs_locs_report_id_476fc202" ON "ie_report_obs_locs" ("report_id");
CREATE INDEX "ie_report_obs_locs_loc_id_df22e215" ON "ie_report_obs_locs" ("loc_id");
ALTER TABLE "ie_report_obs_times" ADD CONSTRAINT "ie_report_obs_times_report_id_time_id_82f0bbaa_uniq" UNIQUE ("report_id", "time_id");
ALTER TABLE "ie_report_obs_times" ADD CONSTRAINT "ie_report_obs_times_report_id_d1477056_fk_ie_report_id" FOREIGN KEY ("report_id") REFERENCES "ie_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ie_report_obs_times" ADD CONSTRAINT "ie_report_obs_times_time_id_8ffaae23_fk_ie_time_id" FOREIGN KEY ("time_id") REFERENCES "ie_time" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ie_report_obs_times_report_id_d1477056" ON "ie_report_obs_times" ("report_id");
CREATE INDEX "ie_report_obs_times_time_id_8ffaae23" ON "ie_report_obs_times" ("time_id");
ALTER TABLE "ie_report_obs_types" ADD CONSTRAINT "ie_report_obs_types_report_id_type_id_0deef7b1_uniq" UNIQUE ("report_id", "type_id");
ALTER TABLE "ie_report_obs_types" ADD CONSTRAINT "ie_report_obs_types_report_id_d83fb10b_fk_ie_report_id" FOREIGN KEY ("report_id") REFERENCES "ie_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ie_report_obs_types" ADD CONSTRAINT "ie_report_obs_types_type_id_c78b8f8c_fk_ie_type_id" FOREIGN KEY ("type_id") REFERENCES "ie_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ie_report_obs_types_report_id_d83fb10b" ON "ie_report_obs_types" ("report_id");
CREATE INDEX "ie_report_obs_types_type_id_c78b8f8c" ON "ie_report_obs_types" ("type_id");
COMMIT;